[package]
name = "benchrs"
version = "0.1.0"
authors = ["Arkaitz Jimenez <arkaitzj@gmail.com>"]
edition = "2018"
description = "Apache Benchmark style http bench tool written in async rust"
license = "Apache-2.0"

[dependencies]
smol = "*"
url = "*"
futures = "*"
anyhow = "*"
async-native-tls = "*"
num_cpus = "*"
piper = "*"
httparse = "*"
clap = "*"
log = "*"
simplelog = "*"


[profile.release]
lto = true
