[package]
name = "benchrs"
version = "0.1.0"
authors = ["Arkaitz Jimenez <arkaitzj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smol = "*"
url = "*"
futures = "*"
anyhow = "*"
async-native-tls = "*"
num_cpus = "*"
piper = "*"
httparse = "*"
clap = "*"
log = "*"
simplelog = "*"


[profile.release]
lto = true
