# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags: '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
        - os: macos-latest
          BINFILE: target/release/benchrs
          RELEASE_FILE: macos/benchrs

        - os: ubuntu-latest
          BINFILE: target/release/benchrs
          RELEASE_FILE: linux/benchrs
          
        - os: windows-latest
          BINFILE: target/release/benchrs.exe
          RELEASE_FILE: windows/benchrs.exe

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build release
    - name: Build release
      run: cargo build --release

    # Upload binary
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{matrix.BINFILE}}
        asset_name: ${{matrix.RELEASE_FILE}}
        tag: ${{ github.ref }}
        overwrite: true
